name: Artifacts
on:
    workflow_dispatch:
jobs:
    artifact-producer:
        runs-on: ubuntu-latest
        steps:
          - name: 1. Create Artifact File
            run: |
             echo "This file will be stored in Github Cloud as artifact"
             echo "Generated on $(date '+%F')" >> artifact.txt
             
          - name: 2. Upload the Artifact
            uses: actions/upload-artifact@v4
            with:
                name: artifact-file
                path: artifact.txt

    artifact-consumer:
      runs-on: ubuntu-latest
      needs: artifact-producer
      steps:
        - name: 1. Download Artifact File
          uses: actions/download-artifact@v4
          with:
              name: downloaded-artifact
        
        - name: validate-artifact
          run: cat artifact.txt
             
