name: Dependent job workflow

on:
    push:
        branches:
            - main      
    workflow_dispatch:
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "A job consists of"
            - run: echo "one or more steps"
            - run: echo "that run sequentially"
            - run: echo "within the same runner"
    job-2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Multiple jobs can run in parallel"
            - run: echo "Hello from job 2"
    job-3:
        runs-on: ubuntu-latest
        needs:
            - job-1
            - job-2
        steps:
            - run: echo "Hello from Job 3"
    job-4:
        runs-on: ubuntu-latest
        needs:
            - job-2
            - job-3
        steps:
            - run: echo "Hello from Job 4"
