name: Secrets and Environment Variables

on:
    workflow_dispatch:
jobs:
    staging-environment:
        runs-on: ubuntu-latest
        environment: staging
        env:
            # Inject repository-level secrets and variables
            EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
            EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
            # Inject environment-level secrets and variables
            EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
        steps:
            - name: Inspect Values Inside Job
              run: |
                echo "===== REPOSITORY-LEVEL ====="
                echo "Repo Secret(Masked):  $EXAMPLE_REPOSITORY_SECRET"
                echo "Repo Variable:        $EXAMPLE_REPOSITORY_VARIABLE"
                echo ""
                echo "===== ENVIRONMENT-LEVEL ====="
                echo "Env Secret(Masked):   $EXAMPLE_ENVIRONMENT_SECRET"
                echo "Env Variable:         $EXAMPLE_ENVIRONMENT_VARIABLE"


    production-environment:
        runs-on: ubuntu-latest
        environment: production
        env:
            # Inject repository-level secrets and variables
            EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
            EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
            # Inject environment-level secrets and variables
            EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
        steps:
            - name: Inspect Values Inside Job
              run: |
                echo "===== REPOSITORY-LEVEL ====="
                echo "Repo Secret(Masked):  $EXAMPLE_REPOSITORY_SECRET"
                echo "Repo Variable:        $EXAMPLE_REPOSITORY_VARIABLE"
                echo ""
                echo "===== ENVIRONMENT-LEVEL ====="
                echo "Env Secret(Masked):   $EXAMPLE_ENVIRONMENT_SECRET"
                echo "Env Variable:         $EXAMPLE_ENVIRONMENT_VARIABLE"