name: Step Types

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Shell Hello
      run: echo "Hello from bash!"

  say-hello-inline-python:
    runs-on: ubuntu-latest
    steps:
    - name: 2. Python Hello
      run: print("Hello from Python!")
      shell: python

  say-hello-action:
    runs-on: ubuntu-latest
    steps:
    - name: 3. Actions Hello
      uses: actions/hello-world-javascript-action@10ea8e55c24e3b29834eb4bc3a9b459fb6196678
      with: 
        who-to-greet: "From an action in the GitHub Actions Marketplace"
  
