name: Environment Variables
on:
    workflow_dispatch:
env:
    WORKFLOW_VAR: I_AM_WORKFLOW_SCOPED
jobs:
    job-1:
        runs-on: ubuntu-latest
        env: 
            JOB_VAR: I_AM_JOB_SCOPED
        steps:
           - name: 1. Inspect variable scope for job-1, Step 1
             env:
                STEP_VAR: I_AM_STEP_SCOPED
             run: |
                echo "workflow_var: $WORKFLOW_VAR"
                echo "job_var:  $JOB_VAR"
                echo "step_var: $STEP_VAR"
           - name: 2. Inspect variable scope in job-1, Step 2
             run: |
                echo "workflow_var: $WORKFLOW_VAR"
                echo "job_var:  $JOB_VAR"
                echo "step_var: $STEP_VAR"
    job-2:
        runs-on: ubuntu-latest
        steps:
           - name: 1. Inspect variable scope in job-2, Step 1
             run: |
                echo "workflow_var: $WORKFLOW_VAR"
                echo "job_var:  $JOB_VAR"
                echo "step_var: $STEP_VAR"

